name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Verify pnpm
        run: pnpm -v

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        env:
          VITE_BASE: "/virtual-list-solid-js/"
        run: pnpm build

      - name: Upload Pages artifact
        # Skipping upload-pages-artifact to avoid internal usage of deprecated upload-artifact@v3
        run: echo "Listing .output/public before upload" && ls -la .output/public || true

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: .output/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
